---

- hosts: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
  sudo: yes
  user: ubuntu
  roles:
    - alexeymedvedchikov.rabbitmq
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
    - audit


  vars:
   rabbitmq_create_cluster: yes
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
   rabbitmq_use_longname: 'true'
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'

  tasks:
   - include: tasks/rabbitmq.yml

   - include: tasks/cloudwatch.yml host={{deploy_env}}-rabbitmq1

- hosts: "{{deploy_env}}-rabbitmq2.{{deploy_dns}}"
  sudo: yes
  user: ubuntu
  roles:
    - alexeymedvedchikov.rabbitmq
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
    - audit

  vars:
   rabbitmq_use_longname: 'true'
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
   rabbitmq_create_cluster: yes
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'

  tasks:
   - include: tasks/rabbitmq.yml

   - include: tasks/cloudwatch.yml host={{deploy_env}}-rabbitmq2