---

- hosts: "{{deploy_env}}-rabbitmq1.eq.ons.digital"
  sudo: yes
  user: ubuntu
  roles:
    - warrenbailey.rabbitmq

  vars:
   rabbitmq_create_cluster: yes
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.eq.ons.digital"
   rabbitmq_use_longname: 'true'
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'

- hosts: "{{deploy_env}}-rabbitmq2.eq.ons.digital"
  sudo: yes
  user: ubuntu
  roles:
    - warrenbailey.rabbitmq

  vars:
   rabbitmq_use_longname: 'true'
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.eq.ons.digital"
   rabbitmq_create_cluster: yes
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'
