- hosts: all
  sudo: yes
  remote_user: ubuntu  
  tasks:
   - name: Echo Rabbit into Hostname
     command: echo rabbit > /etc/hostname

   - name: Echo 127.0.0.1 to rabbitmq
     command: echo '127.0.0.1 rabbit' >> /etc/hosts

   - name: Change the hostname
     command: hostname -F /etc/hostname

   - name: Create rabbitq source  file
     command: sudo touch /etc/apt/sources.list.d/rabbitmq.list

   - name: Add write permissions to source file
     command: sudo chmod a+w /etc/apt/sources.list.d/rabbitmq.list

   - name: Cat Debian resource location to file
     command: sudo echo 'deb http://www.rabbitmq.com/debian/ testing main' > /etc/apt/sources.list.d/rabbitmq.list

   - name: Remove write permissions
     command: sudo chmod a-w /etc/apt/sources.list.d/rabbitmq.list

   - name: Get the public key for rabbit mq repo
     command: sudo curl https://www.rabbitmq.com/rabbitmq-signing-key-public.asc -o /tmp/rabbitmq-signing-key-public.asc

   - name: Add the public key
     command: sudo apt-key add /tmp/rabbitmq-signing-key-public.asc

   - name: Delete the public key
     command: sudo rm /tmp/rabbitmq-signing-key-public.asc

   - name: apt-get update
     command: sudo apt-get -qy update

   - name: Install RabbitMQ
     command: sudo apt-get -qy install rabbitmq-server

  post_tasks:
   - name: Add users
     command: sudo rabbitmqctl add_user survey_runner changeit

   - name: Set Permissions
     command: sudo rabbitmqctl set_permissions survey_runner '.*' '.*' '.*'
