---

- hosts: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
  sudo: yes
  user: ubuntu
  roles:
    - warrenbailey.rabbitmq
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'

  vars:
   rabbitmq_create_cluster: yes
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
   rabbitmq_use_longname: 'true'
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'

  tasks:
   - rabbitmq_plugin: names=rabbitmq_management state=enabled

   # remove the default 'guest' user who has administrator access
   - rabbitmq_user: user=guest
                    state=absent

   # Create a user who can write to the queues
   - rabbitmq_user: user={{rabbitmq_write_user}}
                    password={{rabbitmq_write_password}}
                    force=yes
                    vhost=/
                    write_priv=.*
                    configure_priv=.*
                    read_priv=.*
                    state=present

   # Create a user who can read from queues
   - rabbitmq_user: user={{rabbitmq_read_user}}
                    password={{rabbitmq_read_password}}
                    force=yes
                    vhost=/
                    read_priv=.*
                    write_priv=.*
                    configure_priv=.*
                    state=present


   # Create an admin user
   - rabbitmq_user: user={{rabbitmq_admin_user}}
                    password={{rabbitmq_admin_password}}
                    force=yes
                    vhost=/
                    configure_priv=.*
                    read_priv=.*
                    write_priv=.*
                    state=present
                    tags=administrator


- hosts: "{{deploy_env}}-rabbitmq2.{{deploy_dns}}"
  sudo: yes
  user: ubuntu
  roles:
    - warrenbailey.rabbitmq
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'

  vars:
   rabbitmq_use_longname: 'true'
   rabbitmq_cluster_master: "{{deploy_env}}-rabbitmq1.{{deploy_dns}}"
   rabbitmq_create_cluster: yes
   rabbitmq_ha_enabled: yes
   rabbitmq_ha_mode: all
   rabbitmq_ha_pattern: '.*'

  tasks:
   - rabbitmq_plugin: names=rabbitmq_management state=enabled

   # remove the default 'guest' user who has administrator access
   - rabbitmq_user: user=guest
                    state=absent

   # Create a user who can write to the queues
   - rabbitmq_user: user={{rabbitmq_write_user}}
                    password={{rabbitmq_write_password}}
                    force=yes
                    vhost=/
                    write_priv=.*
                    configure_priv=.*
                    read_priv=.*
                    state=present

   # Create a user who can read from queues
   - rabbitmq_user: user={{rabbitmq_read_user}}
                    password={{rabbitmq_read_password}}
                    force=yes
                    vhost=/
                    read_priv=.*
                    write_priv=.*
                    configure_priv=.*
                    state=present

   # Create an admin user
   - rabbitmq_user: user={{rabbitmq_admin_user}}
                    password={{rabbitmq_admin_password}}
                    force=yes
                    vhost=/
                    configure_priv=.*
                    read_priv=.*
                    write_priv=.*
                    state=present
                    tags=administrator
