---

- hosts: all
  user: ubuntu
  roles:
    - warrenbailey.rabbitmq
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
